* 背景及意义
由中电联发布的2019 - 2020年度全国电力供需形势分析预测报告可知，2019年国内全年全社会用电量7.23万亿千瓦时，比上年增长4.5%，2020年电力消费将延续平稳增长态势，全社会用电量增长4% - 5%，预计年底发电装机容量21.3亿千瓦，其中火电仍将为最大占比，且在火电装机中，煤电所占比例最大[1]。煤炭是我国的主要化石能源，而燃煤电厂对煤炭的需求量是全国煤炭需求量的一半左右[2]。由此易知，火力发电在未来仍将占比较高，燃煤机组仍将占据主导地位。近年来我国对经济能源结构进行了调整，风电、太阳能和核电等新能源占比上升明显，2020年是“十三五”规划的收官之年，全面推动煤电机组灵活性改造，提升燃煤机组运行稳定性效益性成为火力发电的重中之重。火焰稳定性是火焰稳定燃烧的基础，电站锅炉燃烧的基本要求是在炉膛内建立并维持稳定、均匀的燃烧火焰，燃烧火焰是表征燃烧状态稳定与否最直接的反映[3]。燃烧不稳定不仅会降低锅炉热效率，产生污染物、噪声等，而且在极端情况下可能引起锅炉炉膛灭火，如若处理不当甚至会诱发炉膛爆燃造成事故，造成设备的严重损伤，对工作人员的人身安全带来危险，影响电厂运行的安全性和经济性。因此，对炉内燃烧工况进行实时、可靠的监测，是有效地避免在燃烧不稳定工况下发生炉膛爆炸及温度场分布异常等安全事故的有效手段[4]。为了预防这种潜在的危险必须进行切实有效的火焰检测和燃烧诊断，火焰检测包含了两个含义，即火焰是否存在和燃烧是否稳定，后者属于燃烧诊断问题，因而更具有实用意义[5]。火焰可视化和表征技术是深入了解煤粉燃烧的重要研究工具之一，旨在保证燃烧过程安全运行的同时减少未燃尽碳损失和污染物排放[6]。研究燃烧系统火焰稳定性的最终目的是达到最优的燃烧过程，降低污染物排放，提升电厂的安全运营。
近年来，随着计算机视觉技术方法的飞速崛起，将机器学习、深度学习等人工智能算法结合数字图像处理技术应用于炉膛燃烧状态监测已经成为众多学者关注的热点。现有的火焰图像监测技术主要是将数字图像处理技术与人工智能算法结合，通过传统特征提取技术或者深度学习方法提取火焰图像的特征并利用其建立基于数据驱动模型来监测锅炉燃烧过程，并根据特征参数结合机器学习算法判断炉膛内部煤粉燃烧稳定性状况。
* 国内外研究动态
这些年来国内外学者对采用图像处理技术的火焰检测和诊断进行了一系列探索。通过火焰图像来对火焰进行监测和诊断是一种比较创新且高效的研究方法。目前在火焰图像处理的研究中，研究者的研究焦点主要聚焦在图像处理和人工智能方法相结合的燃烧状态识别与诊断[7]。
对电站锅炉内火焰进行监测是保证电站锅炉正常运行的重要组成部分，目前，对炉膛火焰监测手段主要在CCD技术上[8]。基于CCD技术的非接触式火焰监测是现代光电图像检测技术、数字图像处理技术和热辐射理论的三者相结合的炉膛火焰监测方法。该方法具有快速响应、实时在线监测、信息和数据远程共享等优势已经被广泛的应用到燃煤电站火焰监测之中。
日本三菱公司[9]研制开发除了新一代的火焰检测装置光学影像火焰扫描仪。该火焰监测器和检测原理采用了摄像机和传像光纤直接拍摄火焰图像，并利用图像信息处理判断火焰的稳定性。该技术在日本广岛电厂及香港拉码电厂进行了首次运行以来，以其拥有先进的技术和可靠的性能展现出了良好的应用前景。
美国ABB-CE公司[10]开发了SS1（Safe Scanl）的燃烧诊断装置应用于大型电站锅炉的燃烧诊断。该装置对传统的UV摄像头在低锅炉负荷下的不敏感性进行了改进，提出了用可见光区域的光导纤维及光电转化装置对火焰型号的频率和强度进行了探测分析，从而得出火焰的状态。为了避免高温对光纤的损坏，将光纤布置在二次风口。
芬兰IVO公司[11]开发了燃烧检测与数字分析系统DIMAC（Digital Monitoring and Analysis of Combustion）。该系统通过改进锅炉燃烧效率和可靠性来改善安全性和减少NOx的排放，DIMC系统自动存储单喷嘴或者整个锅炉卸负荷时最后两分钟的测量和计算结果，可以帮助运行人员发现事故的原因，同时运行人员也可以随时存入当前的工况和数值模拟数据库中。这些信息有助于比较不同煤种之间的燃烧质量。
在国内，清华大学的吴占松等人[12]最早利用CCD图像传感器进行温度测量，并开展了非对称火焰三维温度场分布重建研究。
周怀春等人[13]最初利用双色法温度计从火焰辐射能量分布中求出火焰的二维的温度场分布，并根据温度场的信息对燃烧状况进行诊断。之后该课题组基于二维火焰温度场分布及逆辐射原理实现了三维温度场重建[14]。
浙江大学王飞等人[15-17]以简化的辐射传递方程模型，根据CCD的光电转换对图像进行处理，实现了对炉内燃烧区域某一断面的温度场重建。利用提出了基于彩色CCD相机的信息，运用比色法的原理对温度场的重建。
中科院工程热物理研究所郭建民等人[18, 19]利用CCD摄像机对炉膛温度进行了测量，并对锅炉负荷、过量空气系数、煤种、炉膛温度和燃烧器运行方式等因素同锅炉NOx排放特性之间的关系进行了实验研究。表明CCD摄像机测温能够实时的检测炉膛温度，诊断局部高温，进而改进燃烧，调整运行工况，有效降低NOx排放。
上海理工大学蔡小舒等人[20, 21]利用标定后的光谱仪系统对燃煤电站火焰进行了检测，并通过非线性最小二乘法拟合求得火焰视场的平均温度。该方法是基于燃煤火焰的灰体辐射特性假设，即假设燃煤火焰在 500~900nm 波段内发射率是一个定值。
南京自动化研究所许柯夫[22]推导了火焰辐射测温公式并进行了基于火焰辐射图像的燃烧诊断的初步研究，探讨了基于火焰辐射图像处理的燃烧温度图像检测的方法，利用比色测温的原理，消去中心介质吸收的影响，不需要进行黑体标定便可以进行辐射温度的测量。
东南大学王世民等人[23, 24]也在从事炉内火焰图像处理的研究工作，提出的系统对于火焰图像数据进行动态处理，进而获得火焰的亮度均值、面积和形心坐标等参数，可根据炉内燃烧程度及发展趋势，提前报警。
浙江大学热能工程研究所岑可法院士等人[25-27]基于火焰辐射图像的三色信息，提出了二维温度场的测量方法，此外，他们还建立了截面温度场和火焰燃烧颗粒浓度场的重建模型，并在此基础上开展了燃烧智能诊断的研究。
安徽大学特种电视技术研究中心的吴海滨教授等人[28]提出了基于彩色三基色测温技术和数字图像处理技术实现对炉内火焰的可视化检测，开发了炉内火焰温度分析系统，该系统将内窥式高温工业电视和炉膛火焰温度检测系统有机的结合起来，操作人员能在计算机前实时监视炉内点火、燃烧等工况，系统还能提供炉膛熄火、燃烧稳定性、火焰中心偏移、火焰形态、燃烧趋势等信息。
Jones[29]提出了煤粉燃烧过程中的中间产物浓度直接影响火焰光谱的特征波长。
Shimoda[30]通过定性分析指出，燃烧火焰检测的辐射波长应该在6000~7000埃之间进行，当波长小于5500埃时燃烧火焰的信噪比很小，而当燃烧火焰的波长大于7000埃时，周围热环境的辐射信号很强，检测信号不能正确的反应燃烧工况的变化。
Huang等人[31-33]利用火焰的频谱分布特性计算火焰的闪烁频率，这种方法很好的表征了火焰的闪烁特点。
英国Kent大学卢钢[34]，运用双色法对燃烧系统内的火焰参数进行了实时测量，实现在线识别煤种的功能。
英国Kent大学的闫勇[35]等开展了火焰图像处理研究工作，对火焰温度、烟黑浓度和火焰形状进行了多方面的实验研究。
卫成业等人[36]采用Kohonen自组织神经网络和BP神经网络相结合的算法来实现对燃烧状态的监测。前者用来判断燃烧状态，后者实现预测诊断功能。根据采集的单角燃烧器火焰图像，选取了四个特征变量进行燃烧状态的判断。Kohonen自组织神经网络对燃烧状态进行聚类，将燃烧状态分为四类。最后将聚类结果放入BP神经网络进行训练，达到对燃烧状态的预测功能。
刘禾[37]研究了关于燃煤锅炉的燃烧稳定性判别问题，在动态图像上提取了燃烧稳定性特征参数，在用着火位置相对变化量描述燃烧稳定性的基础上，研究了利用模糊神经网络进行燃烧稳定性判别的方法，故障诊断模块采用了由3层BP神经网络建立的诊断模型；并将燃烧状态判别为稳定、较稳定、欠稳定和不稳定4种状态。该方法利用模糊神经网络获取专家判别经验，并可通过网络学习调整判别规则以适应各种燃烧状况，判别方法能有效地进行燃烧稳定性判别。这对实现燃烧状态自动监测，保障锅炉安全运行具有实际意义。
徐宝昌等人[38]针对锅炉燃烧监控系统所采集的火焰动态图像，提出了一种基于在线模糊聚类算法的炉内火焰燃烧诊断方法。该方法分析了火焰图像的特点，提取了判别火焰稳定性的特征量，以提取的特征量作为在线模糊聚类算法的输入参数，分析燃烧图像的隶属度，给出判别标准对燃烧稳定性进行综合评估，但判别标准的可行性还有待进一步验证。
Liu等人[39]提出了一种支持向量机算法来监测炉膛火焰的状态。根据数字图像处理技术提取火焰特征量构成一组向量，然后使用支持向量机分类算法对燃烧火焰进行分类。利用该方法对火焰图像进行分析，可以有效地确定燃烧状态的燃烧状态。
吴一全等人[40]将Krawtchouk矩引入火焰特征提取，将Krawtchouk矩不变量与小波支持向量机相结合的火焰燃烧状态识别方法。采用支持向量机算法对火焰图像进行状态识别；并采用混沌小生境粒子群算法优化支持向量机中的核函数与惩罚银子，使识别性能达到最优。
Li等人[41]利用图像处理技术提取图像特征，采用极限学习机（Extreme learning machine，ELM）判断燃烧状态。其均采用图像分割技术对火焰图像进行分割，随后提取火焰特征，建立极限学习机模型，对回转窑内火焰的状态进行识别。
Wang[42]提出了一种新的基于深度学习的方法来识别炉膛燃烧状态和测量放热率。通过端到端网络，特征提取和燃烧状态分类被集成到一个框架中。深度学习模型将火焰图像转化为多层DNN（深度神经网络）或CNN（卷积神经网络），以同时预测燃烧状态和热释放速率。
* 课题研究内容
近年来，深度学习受到了前所未有的关注和发展，它最大的优点就是可以自动学习数据中具有代表性的特征，有效避免了由传统特征提取方法所带来的误差，因此被广泛应用于与特征提取相关的研究领域。SIFT（Scale-invariant feature transform）即尺度不变特征变换，在尺度空间寻找极值点，提取位置、尺度、旋转不变量，可在图像中检测出关键点，是一种局部特征描述子，对旋转、尺度缩放、亮度变化保持不变性，对视角变化、仿射变换、噪声也保持一定程度的稳定性。SIFT算法具有多量性和可扩展性，独特性好，信息量丰富，在图像处理和计算机视觉领域有着很重要的作用，因此基于SIFT算法的火焰检测具有广阔的应用前景。
接下来我将从以下几个方面来展开我的工作。
提取数据：
火电厂一天中机组的负荷是变化的，不同的燃烧负荷最直观的是锅炉给煤量的不断变化，导致炉膛燃烧状况也随着运行的调整不断变化。从火电厂通过测量不同给煤量下燃烧火焰的状态值，提取不同燃烧工况下的各种燃烧状态数据段。
处理数据：
1. 定量稳定性指标表征火焰图像
分析火焰图像的颜色、纹理、轮廓、运动特征等图像特征，在总结之前提出的基于深度学习方法的对炉膛燃烧火焰图像所进行的分析的基础上，引入火焰的扩散速度，利用SIFT算法提取火焰前后帧的相似点，得到相对坐标系的位移，由于已知前后帧火焰图像的时间间隔，可计算出火焰的扩散速度，从而建立稳定性指标，表征火焰图像。
2. 建立燃烧指标定量燃烧稳定性
根据不同工况下采集到的火检数据和燃烧原理，按照现场运行人员的经验（例如给煤量变化），对燃烧状态进行分类，划分出燃烧不稳定区间、稳定区间和灭火区间，将表征火焰图像的特征变量输入到深度学习LSTM神经网络中进行学习训练，建立稳定性模型，分析比较使用不同工况下建立的燃烧稳定性指标与实际运行经验的是否相符，实现对燃烧状态的判别。
* 研究方案及难点
在燃煤机组炉燃烧稳定性检测中，火焰可视化和表征技术是深入了解煤粉燃烧的重要研究工具之一，旨在保证燃烧过程安全运行的同时减少未燃尽碳损失和污染物排放。由于火焰具有动态复杂性，现有的火焰图像监测技术主要是将数字图像处理技术与人工智能算法结合，通过传统特征提取技术或者深度学习方法提取火焰图像的特征并利用其建立基于数据驱动模型来监测锅炉燃烧过程。
首先，分析燃烧稳定性的研究成果及相关方法，总结归纳稳定性的判断依据和常用方法。
其次，研究火焰图像与燃烧稳定性之间的关系，分析火焰图像特征与燃烧稳定性的定量关系。
再次，研究SIFT算法，了解SIFT提取火焰图像特征的原理，分析用于燃烧稳定性判别所需的表征特征，引入扩散速度更深层地表征火焰图像。
然后，研究提取特征与燃烧稳定性之间的定量关系，得出燃烧、不稳定、灭火所对应的特征区间，将表征火焰图像的特征变量输入到深度学习LSTM网络中进行学习。
最后，使用前面提出的燃烧稳定性判别方法，对火电厂实际数据进行测试，从而验证该方法的有效性。
* 预期成果和可能的创新点
在对燃煤机组炉膛火焰图像的特性，包括颜色、纹理、轮廓、运动特征等图像特征进行分析总结的基础上，引入火焰的扩散速度，利用SIFT算法提取火焰前后帧的相似点，得到相对坐标系的位移，计算出火焰的扩散速度，从而建立稳定性指标，表征火焰图像，将表征火焰图像的特征变量输入到深度学习LSTM网络中进行学习，建立稳定性模型，实现对燃烧稳定性的判别。
其中，可能的创新点有：一种新的基于深度学习的对炉膛火焰图像进行特征提取的方法；建立燃烧指标定量表示燃煤机组炉膛燃烧稳定性；建立对应的火焰稳定性与图像检测值之间的定量关系。
* 论文工作计划
论文工作的总体时间安排：
1. 2020年9月，开题准备工作，查找燃煤机组炉膛火焰检测与诊断的相关资料，了解国内外的发展动态，对课题进行可行性分析，确定课题的最终研究方向及课题内容。
2. 2020年10月―2021年12月，进行深入分析，认真学习与本研究课题相关的理论知识。
3. 2021年1月―2021年2月，进行相关模型的概要设计和实验环境的搭建。
4. 2021年3月―2021年10月, 完成对相关算法的改进，并进行试验，验证有效性。
5. 2021年10月―2021年12月，总结和整理相关资料，进行论文的撰写，准备答辩。
* 参考文献
[1] 中电联. 2019-2020年度全国电力供需形势分析预测报告[Z]. 2020. 
[2] 段志强. 低负荷稳燃技术在燃煤锅炉中的应用[J]. 山东工业技术, CNKI: SUN: SDGJ. 0. 2019-05-174. 
[3] MALMGREN A, RILEY G. 5.04 - Biomass Power Generation[J]. SAYIGH A. Oxford: Elsevier, 2012: 27-53. 
[4] 佘星星, 黄福珍. 锅炉火焰图像特征及燃烧状态智能监测综述[J]. 上海电力学院学报, 2010, 26(4): 399-405. 
[5] 吕震中, 沈炯. 电站锅炉火焰检测及燃烧诊断技术[J]. 锅炉技术, 1997(05): 8-14. 
[6] 张清宇. 火焰燃烧稳定性诊断方法研究[D]. 浙江大学, 2004. 
[7] 周怀春, 罗自学,  娄春. 辐射能信号作为锅炉燃烧及机组运行重要监控参数的分析[J]. 动力工程学报, 2010, 30(8): 593-600. 
[8] 刘家汛. 辐射光谱法电站锅炉燃烧检测诊断研究[J]. 2014, 上海理工大学, 2055-2059. 
[9] 舒子恺. 三菱新型火焰监测装置 OPTIS 简介[J]. 热工自动化信息, 1993.1. 
[10] 高翔, 骆仲泱. 电站锅炉燃烧实时诊断应用技术[J]. 电站系统工程, 1998(3): 52-54. 
[11] Han C.Y. Experimental Study on Diagnosis Pulverized Coal Combustion by Flame Monitoring[J]. Power Engineering, 1993. 
[12] 吴占松. 发光火焰的图像处理及其在燃烧检测中的应用[J]. 1988, 清华大学. 
[13] 娄春, 周怀春,  姜志伟, 等. 炉膛内断面温度场与辐射参数同时重建实验研究[J]. 中国电机工程学报, 2006, 26(14): 98-103. 
[14] 周怀春, 娄新生, 邓元凯. 基于辐射图象处理的炉膛燃烧三维温度分布检测原理及分析[J]. 中国电机工程学报, 1997(01): 1-4. 
[15] 王飞, 马增益, 严建华, 等. 运用计算机图像处理和神经网络技术对炉膛火焰进行诊[J]. 热力发电, 2003(02): 24-28. 
[16] 王飞, 薛飞, 马增益, 等. 运用彩色CCD双色信息测量燃烧火焰的温度场[J]. 发电设备, 1998(06): 2-5+47. 
[17] 王飞,  严建华,  卫成业,  等.  基于图像处理的燃烧诊断和温度场测量系统在 300MW 电站锅炉上的应用[J].  热力发电, 2001(03): 26-29
[18] 郭建民, 刘石,  姜帆, 等. 基于 SVM 的对冲燃煤锅炉NOx排放特性[J]  燃烧科学与技术, 2006(03): 243-247. 
[19] 郭建民, 刘石, 姜帆, 等. 利用CCD测量炉膛温度场及NOx 排放特性试验研究[J]. 热能动力工程, 2006(01): 39-42+106. 
[20] 蔡小舒, 罗武德. 采用发射光谱法检测煤粉锅炉火焰的技术研究[J]. 动力工程学报, 2000(06): 955C959+983. 
[21] 蔡小舒, 罗武德. 光谱法测量煤粉火焰温度和黑度的研究[J]. 工程热物理学报, 2000(06): 779-782.
[22] 许柯夫. 数字图像处理技术在电厂锅炉燃烧检测中的应用[J]. 电力系统自动化, 1995, 19(4): 43-47. 
[23] 王式民, 吕震中, 麻庭光. 图像处理技术在全炉膛火焰检测中的应用[J]. 动力工程学报, 1996(6): 68C72. 
[24] 王式民, 赵延军, 汪风林. 光学分层热成像法重建火焰三维温度场分布的研究[J]. 工程热物理学报, 2002(s1): 235C238. 
[25] 王飞, 马增益, 卫成业. 根据火焰图像测量煤粉炉截面温度场的研究[J]. 中国电机工程学报, 2000, 20(9): 67C71. 
[26] 白卫东, 严建华, 池涌. PCA和SVM在火焰检测中的应用研究[J]. 中国电机工程学报, 2004, 24(2): 185C190. 
[27] 卫成业, 严建华, 商敏儿. 利用面阵CCD进行火焰温度分布测量(I)C二维投影温度场的测量[J]. 热能动力工程, 2002, 17(1): 58C61. 
[28] 张琴. 炉内火焰温度分析系统的研究[D]. 安徽省: 安徽大学, 2010. 
[29] JONES A R. Flame Failure Detection and Modern Boilers[J]. Journal of Physics E: Scientific Instruments, 1988, 21(10): 921C928. 
[30] SHIMODA M, SUGANO A, KIMURA T, 等. Prediction Method of Unburnt Carbon for Coal Fired Utility Boiler Using Image Processing Technique of Combustion Flame[J]. IEEE Transactions on Energy Conversion, 1990, 5(4): 640C645. 
[31] HUANG Y, YAN Y, LU G, 等. On-Line Flicker Measurement of Gaseous Flames By Image Processing and Spectral Analysis[J]. Measurement Science and Technology, 1999, 10(8): 726C733. 
[32] XU L, YAN Y, CORNWELL S, 等. On-line fuel identification using digital signal processing and fuzzy inference techniques[J]. IEEE Transactions on Instrumentation and Measurement, 2004, 53(4): 1316C1320. 
[33] XU L, YAN Y. An improved algorithm for the measurement of flame oscillation frequency[J]. IEEE Transactions on Instrumentation and Measurement, 2007, 56(5): 2087C2093. 
[34] LU G, YAN Y, RILEY G, 等. Concurrent Measurement of Temperature and Soot Concentration of Pulverized Coal Flames[J]. IEEE Transactions on Instrumentation and Measurement, 2002, 51(5): 990C995. 
[35] BHEEMUL H C, LU G, YAN Y. Three-dimensional visualization and quantitative characterization of gaseous flames[J]. Measurement Science and Technology, 2002, 13(10): 1643C1650.
[36] 卫成业, 严建华, 商敏儿. 利用面阵CCD进行火焰温度分布测量(I)C二维投影温度场的测量[J]. 热能动力工程, 2002, 17(1): 58C61. 
[37] 刘禾. 基于火焰图像和模糊神经网络的锅炉燃烧稳定性判别[J]. 仪器仪表学报, 2008(06): 1280C1284. 
[38] 徐宝昌, 张丁元, 程亮. 基于图像的火焰稳定性判别方法研究[J]. 计算机工程与应用, 2012, 48(09): 168C171. 
[39] DAO-GUANG L, LI-XIA L, CHANG-LIANG L, 等. Flame Furnace in Thermal Power Plant Condition Monitoring Using SVM[C]. 2009 Second International Conference on Intelligent Computation Technology and Automation. 2009: 67C70. 
[40] 吴一全, 朱丽, 周怀春. 基于Krawtchouk矩阵和支持向量机的火焰状态识别[J]. 中国电机工程学报, 2014, 34(5): 734C740. 
[41] LI W, WANG D, CHAI T. Flame Image-Based Burning State Recognition for Sintering Process of Rotary Kiln Using Heterogeneous Features and Fuzzy Integral[J]. IEEE Transactions on Industrial Informatics, 2012, 8(4): 780C790. 
[42] WANG Z, SONG C, CHEN T. Deep Learning Based Monitoring of Furnace Combustion State and Measurement of Heat Release Rate[J]. Energy, 2017, 131: 106C112.



