* 作者. 题目. 期刊[J]. 年, 卷(期):页码.
** 问题（能够回答两个问题：最终要解决的大问题，本文要解决的特定问题）
** 方法（使用了什么方法，进行了哪些改进或是整合）
** 讨论（对实验结果进行了哪些讨论）
** 结论（注意是否解决了前面提出的特殊问题）
* [2021-11-24 Wed]
** 文章信息
@article{2020A,
  title={A Deep Learning Framework for Hydrogen-fueled Turbulent Combustion Simulation},
  author={An J.and Wang,H.and Liu,B.and Luo,K.H.and Qin,F.and He,G.Q.},
  journal={International Journal of Hydrogen Energy},
  year={2020},
}
** 实验总结
由于CFD的高成本阻碍了其在燃烧相关设计、研究和优化中的应用，本文提出了一基于深度学习方法的湍流燃烧模拟框架。
基于U网络结构和初始化模块，设计了一种优化的深度卷积神经网络(CNN)，用于构建深度学习求解器的框架，称为CFDNN。利用不同进口速度的空腔内氢气燃烧的模拟结果对CFDNN进行训练。其结果与OpenFoam的结果具有很好的一致性，可以准确预测训练集和具有较强的外推能力。在效率方面，相较于传统CFD有2个数量级的加速。
** 具体做法、具体内容
研究对象:空腔内的湍流燃烧。空腔可以理解成燃气轮机燃烧室的简化样机。这种构型包含复杂的物理现象，如湍流与燃烧、着火等之间的强相互作用。
神经网络模型：U-net。由收缩和扩张两部分构成，收缩部分通过使用初始模块进行逐步降维和分解，可以有效地学习复杂的特征，最终映射到k个用户定义的特征空间。扩张部分通过k个定义特征重建图像。
数据集:入口速度在50~202m/s范围内变化，阶跃变化为4m/s(即54、58、62…)。最后，将38个工况的流场数据(包括9种物质的温度、压力和质量分数)转换成矩阵，形成训练集。入口速度在45~210m/s范围内变化，阶跃变化为5m/s(即50，55，60…)的共25个情况的用于测试集（除去了与训练集相同的入口速度）。
损失函数:均方误差。
训练过程：
1).将所有的流场数据转换成一个向量矩阵，然后按特定的顺序形成样本对(由输入和输入目标组成)。例如，t0处的输入是时间t0处的流场数据，而目标是下一时间步t0+Δt处的流场信息，然后将其输出作为另一输入传输回CFDNN。
2).训练集被分为两部分，训练集(80%)和验证集(20%)。验证集用于检查是否发生了过拟合或欠拟合。当均方误差小于1×10^(-4)时，认为训练完成.
3).通过测试集验证。

   
* [2021-12-01 Wed]
** 文章信息
@article{2017Image,
  title={Image-based deep neural network prediction of the heat output of a step-grate biomass boiler},
  author={ Toth, Pal  and  Garami, A.  and  Csordas, Bernadett },
  journal={Applied Energy},
  volume={200},
  number={aug.15},
  pages={155-169},
  year={2017},
}
** 实验总结
因为生物质的燃料组成不均匀和不确定，反应中涉及的化学物种也很多，所以生物质的热化学转化过程是复杂的，该预测系统希望消除或减少在不同负荷下运行的系统中不同燃料质量和高度复杂的燃烧过程所造成的不确定性。基于常规测量的运行参数和实时火焰成像，假设火焰成像可以提供关于燃烧的准瞬时状态的信息，开发了一种基于深度学习的生物质燃烧监测系统，从而补充了通常产生滞后反馈的传统测量。使用深度神经网络提高了预测的准确性，并比浅层神经网络更好地处理了复杂和非线性的预测问题。该系统可以提前30min预测阶梯炉排锅炉的发热量，水温预测精度可达±1℃。

** 具体做法、具体内容
研究对象:3MW阶梯式生物质锅炉（预测输出水温--预测发热量）。锅炉配备了一个集成在分布式控制系统(DCS)中的在线测量系统，该系统可以监测几个运行参数，包括炉膛温度、回水和出水温度、风机转速、锅炉容量和阶梯炉排、燃料供给和清灰系统的液压。另外还安装了一个电化学电池烟气分析仪来记录二氧化碳排放量。用热电偶测量温度。锅炉容量和风机转速以相对值(0-100%)表示。锅炉容量由在线系统根据温度和流量数据计算。风扇转速以最大容量的百分比表示，根据驱动电压计算。锅炉测量系统每10秒产生一组测量值。

输入数据处理:由于获得图像像素较高，如果将每个像素的值作为第一层神经元的输入，受计算资源的限制，本研究获得的全分辨率图像不能实时处理，因此在将输入输入到人工神经网络之前需要进行数据处理。第一步，原始图像的颜色通道(红、绿和蓝)被分离成不同的数据矢量。重建了红色通道的矩阵形式，以计算其平滑的空间梯度。根据空间梯度，计算梯度大小和方向，并将其存储为代表两个虚拟通道的矢量数据。在第二步中，计算包括两个虚拟通道在内的5个通道的前四个统计矩(均值、方差、偏度和峰度)。这些统计矩共20个被用作图像特征，作为输入到人工神经网络的特征集的一部分。
另一部分是DCS系统中测量的数据特征：锅炉容量、输出水温、回水温度、烟气O2含量以及一次（2个）和二次风机的容量。其中预测量是输出水温的未来值，但其当前(瞬时)值也用作输入特征。
摄像机的工作频率为13Hz，一组图像功能大约每80ms可用一次，而DCS收集测量每10秒一次。故10s内取同样的DCS参数与不同的图像参数使用，直到DCS参数更新。

神经网络模型：全连接前馈深度神经网络。输入为上述处理后数据，输出为未来的预测水温。每次摄像机获取图像时，输入都会通过人工神经网络。网络由200个快组成，定义了200个预测，在当前时间和提前28分钟之间线性间隔，每个块都输出对给定时间提前的预测，每个块都可以看作一个独立的深度多层感知器(MLP)，独立于其他块进行训练和评估。

数据集：12小时的测试活动中获得，包含所有测量的操作和图像特征。一半用于训练，一半用于测试。每6个小时具有大约28万个火焰图像和来自锅炉测量系统的2200组数据。

损失函数:为预测和训练数据点之间的均方误差。


* [2021-12-08 Wed]
** 文章信息
@article{2017Image,
  title={Image-based deep neural network prediction of the heat output of a step-grate biomass boiler},
  author={ Toth, Pal  and  Garami, A.  and  Csordas, Bernadett },
  journal={Applied Energy},
  volume={200},
  number={aug.15},
  pages={155-169},
  year={2017},
}
** 实验总结
燃煤锅炉的燃烧机理复杂，输入和输出之间不仅存在着很大的时延，而且还存在着高度的非线性。传统建模方法时间成本高，对操作人员的专业知识水平要求高。更重要的是，随着系统的运行和设备的不断老化，模拟过程与实际物理过程之间的差异会越来越大。
本文提出了一种基于卷积神经网络的燃煤锅炉建模方法，将图像卷积方法和信号系统卷积理论相结合，将DCS记录作为时间序列信号进行燃煤锅炉建模。
同另外2种传统神经网络模型1和模型2的仿真结果进行了详细的比较和分析。与采用简单神经网络的模型1相比，模型2采用带时滞窗口的神经网络明显提高了输出预测效果。卷积映射的神经网络模型的预测误差比模型2的预测误差进一步减小，表明时间维卷积层可以将数据映射到更好的特征空间，有利于建立更精确的锅炉动态特性仿真。

** 具体做法、具体内容
研究对象:燃煤锅炉
数据处理:某火电厂燃煤机组2月份DCS的采样数据。监测对象最多60个，每15分钟记录一次，每天有96个采样点，共计2592条采样记录。
选择4个关键变量作为输出：主蒸汽压力，热效率，烟雾排放，锅炉效率。这些指标不仅与运行参数直接相关，而且相互之间存在耦合关系。由于不同类型的数据数量级相差太大，可进行标准化后使用，即\(S'=S-Smin/Smax-Smin\)。
神经网络模型：该网络由两个卷积层组成，然后是两个完全相连的层，将特征建模为输出。通过最小化代价函数来优化网络中的所有参数，包括卷积核参数。该模型为具有时滞、高度非线性和多变量耦合特性的燃煤锅炉系统建模提供了一种很好的解决方案
损失函数:均为均方差函数

