* 作者. 题目. 期刊[J]. 年, 卷(期):页码.
** 问题（能够回答两个问题：最终要解决的大问题，本文要解决的特定问题）
** 方法（使用了什么方法，进行了哪些改进或是整合）
** 讨论（对实验结果进行了哪些讨论）
** 结论（注意是否解决了前面提出的特殊问题）
* An J.and Wang H.and Liu B.and Luo K.H.and Qin F.and He G.Q.A Deep Learning Framework for Hydrogen-fueled Turbulent Combustion Simulation[J]. International Journal of Hydrogen Energy, 2020.
[[cite:&Wang_2020]]
** 问题
由于CFD的高成本阻碍了其在燃烧相关设计、研究和优化中的应用，本文提出了一基于深度学习方法的湍流燃烧模拟框架。
** 方法
1. 基于U网络结构和初始化模块，设计了一种优化的深度卷积神经网络(CNN)，用于构建深度学习求解器的框架，称为CFDNN。该模型由收缩和扩张两部分构成，收缩部分通过使用初始模块进行逐步降维和分解，可以有效地学习复杂的特征，最终映射到k个用户定义的特征空间。扩张部分通过k个定义特征重建图像。
2. 研究对象:空腔内的湍流燃烧。空腔可以理解成燃气轮机燃烧室的简化样机。这种构型包含复杂的物理现象，如湍流与燃烧、着火等之间的强相互作用。
3. 数据集:入口速度在50~202m/s范围内变化，阶跃变化为4m/s(即54、58、62…)。最后，将38个工况的流场数据(包括9种物质的温度、压力和质量分数)转换成矩阵，形成训练集。入口速度在45~210m/s范围内变化，阶跃变化为5m/s(即50，55，60…)的共25个情况的用于测试集（除去了与训练集相同的入口速度）。
4. 损失函数:均方误差。
5. 训练过程：
   1. 将所有的流场数据转换成一个向量矩阵，然后按特定的顺序形成样本对(由输入和输入目标组成)。例如，\(t_{0}\)处的输入是时间\(t_{0}\)处的流场数据，而目标是下一时间步\(t_{0}+\Delta t\)处的流场信息，然后将其输出作为另一输入传输回CFDNN。
   2. 训练集被分为两部分，训练集(80%)和验证集(20%)。验证集用于检查是否发生了过拟合或欠拟合。当均方误差小于\(1*10^{-4}\)时，认为训练完成。
   3. 通过测试集验证。
** 讨论
1. 对比CFD结果，准确性较高，预测性更好。
2. 新的CFDNN框架需要高级培训，这是计算密集型的。此功能将为需要实时计算的场景提供巨大支持，例如快速设计，甚至燃烧系统的实时控制。
** 结论
其结果与OpenFoam的结果具有很好的一致性。精度方面，可以准确预测训练集和具有较强的外推能力。在效率方面，相较于传统CFD有2个数量级的加速。
* Toth P,Garami A,Csordas B.Image-based deep neural network prediction of the heat output of a step-grate biomass boiler[J]. Applied Energy, 2017, 200(aug.15):155-169.
[[cite:&Toth-et.al._2017]]
** 问题
因为生物质的燃料组成不均匀和不确定，反应中涉及的化学物种也很多，所以生物质的热化学转化过程是复杂的，该预测系统希望消除或减少在不同负荷下运行的系统中不同燃料质量和高度复杂的燃烧过程所造成的不确定性。
** 方法
基于常规测量的运行参数和实时火焰成像，假设火焰成像可以提供关于燃烧的准瞬时状态的信息，开发了一种基于深度学习的生物质燃烧监测系统，从而补充了通常产生滞后反馈的传统测量。

1. 研究对象:3MW阶梯式生物质锅炉（预测输出水温--预测发热量）。锅炉配备了一个集成在分布式控制系统(DCS)中的在线测量系统，该系统可以监测几个运行参数，包括炉膛温度、回水和出水温度、风机转速、锅炉容量和阶梯炉排、燃料供给和清灰系统的液压。另外还安装了一个电化学电池烟气分析仪来记录二氧化碳排放量。用热电偶测量温度。锅炉容量和风机转速以相对值(0-100%)表示。锅炉容量由在线系统根据温度和流量数据计算。风扇转速以最大容量的百分比表示，根据驱动电压计算。锅炉测量系统每10秒产生一组测量值。
2. 输入数据处理:由于获得图像像素较高，如果将每个像素的值作为第一层神经元的输入，受计算资源的限制，本研究获得的全分辨率图像不能实时处理，因此在将输入输入到人工神经网络之前需要进行数据处理。第一步，原始图像的颜色通道(红、绿和蓝)被分离成不同的数据矢量。重建了红色通道的矩阵形式，以计算其平滑的空间梯度。根据空间梯度，计算梯度大小和方向，并将其存储为代表两个虚拟通道的矢量数据。在第二步中，计算包括两个虚拟通道在内的5个通道的前四个统计矩(均值、方差、偏度和峰度)。这些统计矩共20个被用作图像特征，作为输入到人工神经网络的特征集的一部分。

   另一部分是DCS系统中测量的数据特征：锅炉容量、输出水温、回水温度、烟气\(O_{2}\)含量以及一次（2个）和二次风机的容量。其中预测量是输出水温的未来值，但其当前(瞬时)值也用作输入特征。

    摄像机的工作频率为13Hz，一组图像功能大约每80ms可用一次，而DCS收集测量每10秒一次。故10s内取同样的DCS参数与不同的图像参数使用，直到DCS参数更新。
3. 神经网络模型：全连接前馈深度神经网络。输入为上述处理后数据，输出为未来的预测水温。每次摄像机获取图像时，输入都会通过人工神经网络。网络由200个快组成，定义了200个预测，在当前时间和提前28分钟之间线性间隔，每个块都输出对给定时间提前的预测，每个块都可以看作一个独立的深度多层感知器(MLP)，独立于其他块进行训练和评估。
4. 数据集：12小时的测试活动中获得，包含所有测量的操作和图像特征。一半用于训练，一半用于测试。每6个小时具有大约28万个火焰图像和来自锅炉测量系统的2200组数据。
5. 损失函数:为预测和训练数据点之间的均方误差。
** 讨论
1. 图像响应。与传统的传感器信号相比，图像特征提供了与传统信号相似的瞬时测量，但对过程动态的反应更快。
2. 预测方面。对出水温度的预测相当好。总体趋势和绝对值都在短期内被准确预测(提前到大约5分钟)。然而随着时间推移，误差会增大。对于超过28分钟后的预测，误差会迅速增加，由于数据只是来源于6个小时跨度，模型无法准确学习操作模式，如果能得到周期性的数据，训练效果应该会更好。
3. 模型方面。不同宽度和深度的模型的性能不一样，并没有一个标准的框架。文中讨论了多种不同情况的模型对预测精度的影响。总的来说，增加网络在宽度和深度方面的复杂性可以减少预测的误差，但会增加复杂度和训练难度。
4. 参数。重要性代表了一个给定参数所承载的信息量，更重要的参数往往对输出的影响更大，如文中的输出水温。不同的输入参数需要有不同的权重，典型的输入参数评估方法：Garson算法和灵敏度分析。本文3.5部分有详细讲，分析的各个参数之间的影响强弱判断。

** 结论
该系统采用锅炉在线测量系统和监控炉排的彩色摄像机的输入，用于超前预测输出水温。采用深度、全连接的神经网络并行预测当前时刻往后不同时刻的出水温度，并实时更新，同时输出未来水温的期望值和预测区间。使用深度神经网络提高了预测的准确性，并比浅层神经网络更好地处理了复杂和非线性的预测问题。该系统短期预测误差最小，可以提前30min预测阶梯炉排锅炉的发热量，误差在±1℃。
* Chunming Ouyang,Li Xiao,Zhibin Xu,Weidong Zhang. Research and Simulation of Boiler Combustion System Based on Convolution Neural Network[C]//Proceedings of the 2nd International Conference on Electrical, Control and Automation（ICECA2018）.[出版者不详],2018:504-512.
[[cite:&Ouyang-et.al._2018]]
** 问题
燃煤锅炉的燃烧机理复杂，输入和输出之间不仅存在着很大的时延，而且还存在着高度的非线性。传统建模方法时间成本高，对操作人员的专业知识水平要求高。更重要的是，随着系统的运行和设备的不断老化，模拟过程与实际物理过程之间的差异会越来越大。

本文提出了一种基于卷积神经网络的燃煤锅炉建模方法，将图像卷积方法和信号系统卷积理论相结合，将DCS记录作为时间序列信号进行燃煤锅炉建模。
** 方法
研究对象:燃煤锅炉。

数据处理:某火电厂燃煤机组2月份DCS的采样数据。监测对象最多60个，每15分钟记录一次，每天有96个采样点，共计2592条采样记录。

选择4个关键变量作为输出：主蒸汽压力，热效率，烟雾排放，锅炉效率。这些指标不仅与运行参数直接相关，而且相互之间存在耦合关系。由于不同类型的数据数量级相差太大，可进行标准化后使用，即\(S'=S-S_{min}/S_{max}-S_{min}\)。

神经网络模型：该网络由两个卷积层组成，然后是两个完全相连的层，将特征建模为输出。通过最小化代价函数来优化网络中的所有参数，包括卷积核参数。该模型为具有时滞、高度非线性和多变量耦合特性的燃煤锅炉系统建模提供了一种很好的解决方案。

损失函数:均方误差。
** 讨论
同传统神经网络模型1和模型2的仿真结果进行了详细的比较和分析。与采用简单全连接神经网络的模型1相比，模型2采用带时滞窗口的神经网络明显提高了输出预测效果。卷积映射的神经网络模型的预测误差比模型2的预测误差进一步减小，表明时间维卷积层可以将数据映射到更好的特征空间，有利于建立更精确的锅炉动态特性仿真。
** 结论
本文是一篇分析型的文章，比较了三种神经网络模型，卷积神经网络预测效果最佳。卷积神经网络可以将数据映射到更好的特征空间，有利于建立更精确的锅炉动态特性仿真。
* Shi Y,Zhong W,Chen X,et al. Combustion optimization of ultra supercritical boiler based on artificial intelligence[J]. Energy, 2019, 170(MAR.1):804-817.
[[cite:&Shi-et.al._2019]]
** 问题
传统的锅炉燃烧优化方法主要依靠实验和工厂试验，但是无论是实验室规模的试验还是计划试验，都不能涵盖所有可能的运行条件和控制系统的限制，这就给锅炉燃烧的优化带来了困难。

本文采用人工神经网络和遗传算法相结合的方法对在役660\(MW\)超超临界燃煤电厂锅炉的燃烧进行了优化。

训练样本中有两类参数。第一类是在优化过程中保持不变的固定参数，包括负荷、煤质和过量空气。第二类是优化参数，包括气流组织方案。在优化过程中，有两种类型的参数进入神经网络。
** 方法
1. 研究对象:660\(MW\)超超临界燃煤电厂锅炉。
2. 神经网络模型：文中共使用3个神经网络模型。神经网络1：热效率预测模型、神经网络2：\(NO_{x}\)排放预测模型（本文的目标），神经网络3：排烟温度预测模型（CFD模拟缺乏排烟温度，该参数重要，需要额外生成）。

   前2个模型有两类输入参数，第一类是在优化过程中保持不变的固定参数，包括负荷、煤质和过量空气。第二类是优化参数，包括配风方案（对13个风门开口的控制），输出为相应的预测值。

   第三个模型，输入为电厂负荷、过量空气、燃煤量、空气总量、二次风与一次风比、屏式过热器出口烟道温度，输出为排烟温度。
3. 数据集：
   1) 从锅炉DCS系统中获取了一个月的锅炉数据，数据间隔为20分钟，共计2100组左右。为避免不稳定的运行数据影响结果，只采用20\(min\)内负荷波动在5\(MW\)以内的运行工况数据。最终得到了452组历史运行数据。
   2) 100组CFD模拟产生的数据。
   3) 由于CFD模拟缺少排烟温度，采用452组历史数据结合神经网络3生成的排烟温度数据。
4. 实验方法：通过遗传算法搜索最合适的操作参数组合来优化操作参数，以实现更高的热效率和更低的\(NO_{x}\)排放。
** 讨论
1. 不同样本训练模型的比较，共进行了不同变量下的27组实验。
   1) 使用452个历史运行数据进行训练。
   2) 使用352个历史运行数据和100个CFD模拟数据进行训练。
   3) 使用452个历史运行数据中随机选择的352个历史运行数据来训练。
   4) 使用452个历史运行数据和100个CFD模拟数据进行训练。

   就结果而言，1效果最好，3效果最差。增加数据和使用CFD模拟数据可提高预测精度。
2. 遗传算法的优化，采用不同的交叉率和变异率。\(NO_{x}\)上限为300\(mg/Nm^{2}\)，超过即淘汰。
   1) 交叉率：0.5。变异率：0.08。
   2) 交叉率：0.9。变异率：0.2。
   3) 交叉率：0.9。变异率：0.08。

   结果为2效果最好。

   从400\(MW\)到660\(MW\)的稳定运行工况中间隔每10\(MW\)随机抽取26组历史运行数据验证效果。
** 结论
1. 本文以660\(MW\)超超临界燃煤电厂的历史运行数据和CFD模拟数据为样本，成功地建立了预测其热效率和\(NO_{x}\)排放的人工神经网络模型，且具有相当的准确性。
2. CFD模拟数据的补充进一步提高了模型的精度。
3. 遗传算法将在大约在50步内收敛。
* Ha N Z,Li J,Zhang B,et al. Prediction of combustion state through a semi-supervised learning model and flame imaging[J]. Fuel, 2020, 289(4):119745.
[[cite:&Han-et.al._2020]]
** 问题
由于燃烧火焰本质上具有复杂性和随机性，很难准确预测燃烧状态。尽管通过基于CNN的模型已经取得了各种进展，但这些模型中的一个很大的问题是需要更多的标签数据来进行训练。预测精度还取决于标记数据的规模和质量。

本文提出了一种新的半监督学习模型来预测燃烧状态。该模型是由DAE、GAN和GPC组合而成的。DAE（去噪自动编码器）用于提取特征，GAN用于训练，GPC（高斯过程分类器）用于预测。结构相似度(SSIM)度量侧重于图像结构信息，作为DAE网络的损失函数，可以提高特征提取的效率。
** 方法
1. 研究对象:4.2\(MW\)重油锅炉炉膛。
2. 整体框架：
   第一阶段：数据采集、预处理和分类。火焰图像被分为原始状态和新状态。原始状态的图像被用来训练DAE-GAN。通过新状态的图像对模型进行评估。

   第二阶段：半监督学习模型的建立。无监督学习过程，先用参数初始化模型，然后用原始图像训练，提取需要的特征。有监督学习过程，提取特征用于训练广义预测模型，并进行预测。新燃烧状态用于微调该模型，并通过微调后模型继续预测。
3. 特征提取：
   1) 未标记图像
   2) 标记图像
   3) 新状态标记图像（理论上不可见的新状态）
4. 数据集：从九种不同燃烧状态获得的火焰图像数据集。对于每个燃烧状态，收集了4000个RGB(红、绿、蓝)火焰图像。
   1) A：在固定一次空气(PA)和二次空气(SA)的不同燃料负荷（FL)下的三种不同燃烧状态。
   2) B：只有PA是变化的。
   3) C：只有SA是变化的。
5. 训练方法：数据集A视为原始状态，而数据集B和C被视为新状态。
   1) 从数据集A中随机选择80%的数据来形成训练数据集A1，其余20%的数据用于验证(数据集A2)。
   2) 数据集A1的94%的数据(A3)用于训练DAE-GAN，其余的6%(数据集A4)用于GPC训练。
   3) 对于新状态，DAE-GAN直接使用，GPC需要进一步微调。数据集B和C的结构类似于数据集A的分配方式，即6%的数据用于微调GPC。
** 讨论
1. 数据集A3、B3和C3中随机选取25%组成测试数据集A5、B5和C5用于验证模型的准确性。A5具有较高准确率，且微调后的模型对B5/C5也具有较高精度。可以看出在大量未标注数据和少量标注数据情况下对燃烧状态预测的有效性。
2. 为了详细考察预测精度，记录了9种燃烧状态下的预测结果。总体而言，所提出的半监督学习模型对燃烧状态提供了可接受的精度和可靠的预测。
3. 通过火焰图像的特征分布可视化，表示9种燃烧状态的区分特征。从相同状态提取的图像特征是聚类的，而不同状态下的图像特征被很好地分开。可以得知火焰图像的代表性特征对于可靠、准确地预测燃烧状态起着决定性的作用。
** 结论
通过模型自动提取火焰的深层特征，对相应的燃烧状态进行预测。该方法只需用一小部分标记图像对高斯过程分类器进行微调，就可以预测新的燃烧状态(看不见)，从而大大节省了计算量。主要成果有：
1. 该模型提取深层特征时的抗噪声能力得到提高。
2. 提出了一个新的损失函数LSSIM。探究了最优的迭代次数和损失率。
3. 该模型具有更好的预测精度，可用于工业应用。
4. 该模型表现出很强的鲁棒性和泛化能力，并且可以很容易地进行微调来预测燃烧稳定性和排放。
* 参考文献                                                           :ignore:
bibliographystyle:unsrt
bibliography:./papers.bib
