* [2020-11-06 周五]
** Done
1. 完成并提交了开题报告和文献综述
** Question
无
** Plan
1. 处理火焰视频数据
* <2020-10-23 周五>
** Done
1. 阅读《Real-Time Fire Detection Based On Deep Convolutional Long-Recurrent Networks And Optical Flow Method》、《Optical Flow Feature Based for Fire Detection on Video Data》、《高炉内煤粉燃烧速度场的数值模》、《混煤燃烧特性研究及燃烧速度预测》。
2. 找图片拼接的示例，示例所用为SIFT算法和FLANN函数库。
** Question
1. 阅读文章中没用利用光流法提取图像相似点从而计算扩散速度的应用。
2. 运行示例代时，错误提示为 ModuleNotFoundError: No module named 'cv2' ，经检查已安装OpenCV和OpenCV-python模块，仍提示相同错误类型，故未能跑通示例代码。
** Plan
1. 找SIFT算法示例并跑通。
2. 截取视频数据的火焰图像。
3. 修改开题报告中课题研究内容、研究方案及难点、预期成果和可能的创新点，使其更加详细。
4. 写文献综述。
* <2020-10-16 周五>
** Done
1. 找计算相似点的代码，并运行例子
2. 阅读《Optical Flow Estimation for Flame Detection in Videos》、《Dynamic Feature-based Fire Detection Using Fusion of Markov Random Field and PCA Optical Flow》、《基于光流动态特征与 SVM 的阴燃火检测方法》、《FIRE AND SMOKE DETECTION IN VIDEO WITH OPTIMAL MASS TRANSPORT BASED OPTICAL FLOW AND NEURAL NETWORKS》、《基于光流法火灾烟雾视频图像识别及多信息融合探测算法研究》
** question
1. 所找计算相似点的示例为计算前后图片的相似性，不符合课题设想中计算图片相似点的应用想法
2. 阅读文章中没有解决类似问题的文章
** Plan
1. 找图片拼接的示例
2. 找所阅读文章中的开源代码
* <2020-10-09 周五>
** Done
1. 提交开题报告
** Question
1. 具体方法未确定
** Plan
1. 尽快确定具体方法
* [2020-09-25 Fri]
** Done
1. 阅读《基于特征传播的髙速视頻中物体检测》、《基于特征融合的高准确率视频中物体检测》、《基于递归特征融合与自适应特征提取的高速高准确率视频中物体检测》
2. 阅读《Deep Feature Flow for Vedio Recognition》, 《Flow-Guided Feature Aggregation for Vedio Object Detection》, 《An Empirical Study of Spatial Attention Mechanisms in Deep Networks》, 《Towards High Performance Vedio Object Detection》
** Question
1. 所看文章的方法中所用方法（语义分割及目标检测）运用到课题里较为困难
** Plan
1. 阅读检测图像/视频中物体速度的文献
2. 阅读检测图像/视频前后帧相似点的文献
* [2019-09-06 Fri]
** Done
1. Read "The Promise of Artificial Intelligence in Chemical Engineering: Is It Here, Finally?".
2. Revise the patent about combustion steady estimation.
** Quesions
1. Need new ideas of AI applications for power plants.
** Plan
1. Commit the patent about combustion steady estimation.
2. Check combustion steady monitoring function.
   
